services:
  url-shortener:
    build: .
    container_name: url-shortener
    restart: always
    volumes:
      - url-data:/data
    ports:
      - "5000:5000"
    environment:
      - DB_PATH=/data/urls.db
    networks:
      - app-network

  url-shortener-auth:
    build: .
    container_name: url-shortener-auth
    restart: always
    volumes:
      - url-data:/data
    ports:
      - "5001:5001"
    environment:
      - DB_PATH=/data/urls.db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8800:8800"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - url-shortener
      - url-shortener-auth
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  url-data:
    driver: local